org: drfword
app: testy
service: aws-python-project

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.10

plugins:
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    httpPort: 3000

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: post
          integration: lambda-proxy
          cors: true
